sudo: required
language: node_js
node_js:
   - "6"
   - "8"
   - "10"
after_script:
  - npm run-script coveralls
notifications:
  irc:
    - "chat.freenode.net#beagle-bonescript"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/800e4efb92aa7f8eda15
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


